### ISSUE TITLE
Your ActivityIndicator custom renderer is overriding the default

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#10]
Your Xamarin.Judopay nuget has a custom render in it for the default xamarin.forms `ActivityIndicator` which shows an indeterminate progress bar instead.  

Any usage of `ActivityIndicator` in our app is overriden by your renderer.
Please, create a custom class inheriting `ActivityIndicator` and make a renderer out of it rather than overriding the default.

This currently breaks our design completely.

**Comment by zfoltin** [comment]
Hey @xleon, thanks for raising this issue. In the next version of the SDK (v 4.3) this custom renderer will be removed 🙅‍♂️ I'll let you know when it's released (early next week 🤞)

**Comment by zfoltin** [comment]
Hey @xleon, a new version of the SDK has been released with the `ActivityIndicator` fix https://www.nuget.org/packages/Xamarin.JudoPay/4.3.24 🚀 let me know if there are any other issues
