### ISSUE TITLE
Result handler not invoked when payment is declined

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#14]
var paymentPage = new PreAuthPage(_payload);
    paymentPage.resultHandler += PaymentPageHandler;

    private void PaymentPageHandler(object sender, IResult<ITransactionResult> result)
    {
         // whatever   
    }

Using any of the cards aimed for sandbox declined transactions, the `PaymentPageHandler` is never invoked. Instead I get the following alert:

![image](https://user-images.githubusercontent.com/145087/56300049-7f650a80-6135-11e9-9cf6-fe75be05530f.png)

**Comment by xleon** [comment]
@zfoltin

**Comment by zfoltin** [comment]
Hey @xleon, thanks for raising this issue.

So, this is by design on Xamarin currently. We changed this behaviour on native Android to call the handler and close the activity instead of handling declined cards within the SDK. I'll need to chase the business people to see if this is a change they want in the Xamarin SDK too.

**Comment by xleon** [comment]
Hi @zfoltin,
I actually need to tell our backend when a payment has been declined.
It also makes sense that the caller should be responsible to handle errors as we may choose to show the error in a different format (not an alert).

**Comment by zfoltin** [comment]
Hey @xleon, I agree, it makes a lot of sense - hence the change in the native SDK. Good news is that I got the green light to update the SDK and mirror the native behaviour. I'll update you when it's done and a new version is available 🚀

**Comment by xleon** [comment]
Hi @zfoltin,
Any updates on this?

**Comment by zfoltin** [comment]
Hey @xleon, thanks for your patience 🙇. An update is on its way 🏎, hopefully v5.0 will land in a couple of days, addressing not just this but the other open issues as well ✅

**Comment by zfoltin** [comment]
Hey @xleon, sorry for keeping you waiting this long.

Version v5.0 is out now 🚀, please give it a swirl 🌀 and let me know if there is anything good 👼, bad 😠 or ugly 👹 in there.

The theming has somewhat changed to rectify #15 and #16, I'll update the sample app and the wiki here soon to reflect these changes.
