### ISSUE TITLE
Theme ButtonBackgroundColor color not working

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#15]
Hi @zfoltin, looks like it´s a regression on the last nuget as I saw this color working in the previous one.

    Theme = new Theme
            {
                PageTitle = "Card details",
                ButtonLabel = "Authorize payment",
                ShowSecurityMessage = true,
                PrimaryColor = TextColor,
                BackgroundColor = CustomBackgroundColor,
                ButtonBackgroundColor = Color.Red, // <-- not working
                ButtonTextColor = Color.Black,
                HintTextColor = LabelColor,
                LabelTextColor = LabelColor,
                SecondaryTextColor = LabelColor,
                EntryLabelPLaceholderColor = Color.LightGray,
                OverlayColor = CustomBackgroundColor
            }

![image](https://user-images.githubusercontent.com/145087/56356136-4631a680-61d8-11e9-908d-c2af13ab79b8.png)

**Comment by zfoltin** [comment]
Hey @xleon, thanks for raising this issue. I'll be looking into this in the coming days 👍
