### ISSUE TITLE
Support errorColor in the Theme

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#16]
We´d like to be able to change the error color:

![image](https://user-images.githubusercontent.com/145087/56356336-df60bd00-61d8-11e9-9885-51c84881be8d.png)

**Comment by zfoltin** [comment]
Hey @xleon, thanks for raising this issue. I'll be looking into this in the coming days 👍

**Comment by xleon** [comment]
This is not yet solved in 5.0.0. 
I´m using the `ErrorTextColor` property of the `Theme`

**Comment by zfoltin** [comment]
There are a couple of properties that can only be styled through xml on Android - please see the bottom of the updated [wiki page](https://github.com/Judopay/Xamarin-Sample-App/wiki/quickstart) and the [Theme reference](https://github.com/Judopay/Xamarin-Sample-App/wiki/Theme-reference)

**Comment by xleon** [comment]
It works, thanks!!
