### ISSUE TITLE
Cannot compile the app in release

### ISSUE THREAD

**Issue by jpaquete** [Judopay/Xamarin-Sample-App#17]
App does compile and works for Android in debug. In Release does not!. Please can anyone help ? I am in the process of presenting this to clients and cant deploy!...

**Comment by AnthonyLatty** [comment]
This does not describes the error.

**Comment by zfoltin** [comment]
Hi @jpaquete,

Sorry to hear you're having trouble building the sample app in Release mode. Can you share a bit more details about the specific issue so I can try and replicate it? Things like screenshots showing the error or the application output window contents would probably help to pinpoint the issue.

**Comment by jpaquete** [comment]
Hi Mark. I have discovered the situation I will answer my own question on
git. Is was the enable multidex option on visual studio. I also updated all
packages. Thanks and all the best!

A domingo, 21 de abr de 2019, 11:19, Zeno Foltin <notifications@github.com>
escreveu:

**Comment by jpaquete** [comment]
I have figured the situation (after some hours :(.... I cant see my post
though. Is was the enable multidex option on visual studio, My bad I think.
I also updated all packages. Thanks and all the best!
I this that way you can reproduce the situation and document it on the git
project page.
Regards
jpaquete

**Comment by zfoltin** [comment]
Thanks @jpaquete, I've update the sample to have multidex turned on in Release build too. 👍
