### ISSUE TITLE
Passing defaults stopped working on 5.0.0

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#20]
![image](https://user-images.githubusercontent.com/145087/57618136-e3d38800-7582-11e9-93fa-c15e5f0f13e8.png)

As you can see in the image, I´m passing the defaults to the payment page. 
The result is the normal page without any data pre-filled. This was working on the previous version.
The goal of using this functionality is to pass data gathered by a card scanning library.

**Comment by zfoltin** [comment]
Thanks for reporting this @xleon. It seems to be an Android only issue. I'll try and fix it asap!

**Comment by zfoltin** [comment]
Hey @xleon, the latest v5.0.3 version should have the fix for this issue. Please give it a go and let me know if there is anything else amiss.
