### ISSUE TITLE
Ability to customize toolbar 

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#22]
As per the following image, we need the following customizations in the `Theme`:

- Ability to hide or change the toolbar background color
- Ability to hide/remove the tool bar drop shadow
- Ability to change the toolbar text color

![image](https://user-images.githubusercontent.com/145087/57619225-b3d9b400-7585-11e9-8e5b-6a88f8bd9714.png)

**Comment by zfoltin** [comment]
The navigation bar styling is outside of our pages as we only provide ContentPage components. To change the styling of the navigation bar, you can set some properties before `Navigation.PushAsync(paymentPage)` like:
```
((NavigationPage)Application.Current.MainPage).BarBackgroundColor = Color.Black;
((NavigationPage)Application.Current.MainPage).BarTextColor = Color.OrangeRed;
```
See [this post](https://forums.xamarin.com/discussion/95943/how-to-change-navigation-bar-background-color-for-each-content-page) for more details.

Hope this helps
