### ISSUE TITLE
[iOS] Billing Postcode entry not working at Device

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#32]
Steps to reproduce:

- use a release version on the iPhone (as it works fine in debug mode and simulator)
- create and show a pre-auth page
- enter CVV2
- try to enter billing postcode

Result:
- The soft keyboard appears
- I can´t write anything in the billing postcode
- When I navigate back, the soft keyboard remains on screen
- When I repeat the process, an unhandled exception makes the app crash

Expected result:
- I should be able to enter billing postcode and send / authorise pre-auth 
- The keyboard should work fine and disappear when clicking "next" or when navigating back to the previous page
- The app should not crash

We noticed 2 different crashes at our raygun reports

![image](https://user-images.githubusercontent.com/145087/64977702-39fb6380-d8b4-11e9-8c0d-d665ff22d225.png)

![image](https://user-images.githubusercontent.com/145087/64977754-4ed7f700-d8b4-11e9-9bda-ad2a1760071b.png)

**Comment by zfoltin** [comment]
Hey @xleon, thanks for reporting this. I assume you are using the latest version of the SDK and Visual Studio / Xamarin tooling. Can you share which iOS version and which device this is happening on?

**Comment by xleon** [comment]
Xamarin.Forms: 4.1.0.618606
iOS 12.4.1
Device: iPhone 6s

Here´s the xamarin tooling (I´ve just updated to the last preview, but the problem happened before that too. 
---
Visual Studio Community 2019 for Mac (Preview)
Version 8.3 Preview (8.3 build 1760)
Installation UUID: 94fd72ba-b165-42a8-be6d-144ac17f27fa
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000194

Mono Framework MDK
Runtime:
	Mono 6.4.0.194 (2019-06/7da9a041b3b) (64-bit)
	Package version: 604000194

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.0.100-rc1-014190/Sdks
SDK Versions:
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	2.2.300
	2.2.104
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	2.2.5
	2.2.2
	2.1.11

Xamarin Designer
Version: 16.3.0.180
Hash: 54a02e2c9
Branch: remotes/origin/d16-3
Build date: 2019-09-12 15:35:22 UTC

Xamarin.Profiler
Version: 1.6.11.16
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.3 (14492.2)
Build 10G8

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 12.16.1.24 (Visual Studio Community)
Hash: 08809f5b
Branch: d16-3
Build date: 2019-09-06 08:42:42-0400

Xamarin.Android
Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/xleon/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 29.0.0

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/xleon/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-13 13:06:32 UTC

Android Device Manager
Version: 1.2.0.113
Hash: 2f86c05
Branch: remotes/origin/d16-3~1
Build date: 2019-09-13 13:06:52 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803001760
Git revision: 02f4f2e58b5aebe14e078aeff0fbad1abc9c7ae7
Build date: 2019-09-17 11:52:55+00
Build branch: release-8.3
Xamarin extensions: 8f75f12867e7d20d8ca78ea5e136a6ed7dde5dd2

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
LiveXAML 1.3.51

**Comment by zfoltin** [comment]
Thanks for your patience @xleon, a fix is coming up early next week along with other improvements 🚀

**Comment by zfoltin** [comment]
This should be fixed with the latest 5.2 version of the SDK - https://www.nuget.org/packages/Xamarin.JudoPay/5.2.0 🎉

**Comment by xleon** [comment]
working!
thank you
