### ISSUE TITLE
Submit Button is missing on payment page

### ISSUE THREAD

**Issue by TheAlphamerc** [Judopay/Xamarin-Sample-App#7]
On clicking Payment button on samplesPage the payment page is opened  with 3 entry fields but submit button is missing. There is no button on payment screen so that i can submit card credentials.
![screenshot](https://user-images.githubusercontent.com/37103237/49798478-589e5e00-fd68-11e8-903d-b5230c8ce510.jpeg)

**Comment by zfoltin** [comment]
Well, if you enter those credentials you wanted to submit, the button might just magically appear 😃

**Comment by TheAlphamerc** [comment]
I had entered credential several times but submit button didn't appear as you said.

**Comment by aadilsheth** [comment]
Hi @TheAlphamerc 
Could you please perform a screen record of the problem and send your query in to developersupport@judopayments.com

Thank you

**Comment by TheAlphamerc** [comment]
sure
